version: '3'

services:
  nodejs:
    image: docker.pkg.github.com/lucasplath7/react-panda-api/react-panda-api-deploy-image:latest
    container_name: react-panda-api-deploy-image
    restart: unless-stopped
    networks:
      - app-network

  nodewebserver:
    image: nginx:mainline-alpine
    container_name: nodewebserver
    restart: unless-stopped
    ports:
      - "5000:5000"
      # - "443:443"
    volumes:
      - web-root:/var/www/html
      - ./web-nginx-conf:/etc/nginx/conf.d
      - ./web-main-nginx-conf/nginx.conf:/etc/nginx/nginx.conf
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      # - dhparam:/etc/ssl/certs
    depends_on:
      - nodejs
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - nodewebserver
    command: certonly --webroot --webroot-path=/var/www/html --email lucas.plath@gmail.com --agree-tos --no-eff-email --force-renewal -v -d www.react-panda.com -d react-panda.com

volumes:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /root
      o: bind
  # dhparam:
  #   driver: local
  #   driver_opts:
  #     type: none
  #     device: /root/dhparam/
  #     o: bind

networks:
  app-network:
    driver: bridge  