version: '3'

services:
  nodejs:
    env_file: 
      - ./.env
    image: docker.pkg.github.com/lucasplath7/react-panda-api/react-panda-api-deploy-image:latest
    container_name: react-panda-api-deploy-image
    restart: unless-stopped
    networks:
      - node-network

  nodewebserver:
    env_file: 
      - ./.env
    image: nginx:mainline-alpine
    container_name: nodewebserver
    restart: unless-stopped
    ports:
      - "5000:5000"
      - "5001:5001"
      # - "443:443"
    volumes:
      - web-root:/usr/share/nginx/html
      - ./web-nginx-conf:/etc/nginx/conf.d
      - ./web-main-nginx-conf/nginx.conf:/etc/nginx/nginx.conf
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - dhparam:/etc/ssl/certs
    depends_on:
      - nodejs
    networks:
      - node-network

  nodecertbot:
    image: certbot/certbot
    container_name: nodecertbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/usr/share/nginx/html
    depends_on:
      - nodewebserver
    command: certonly --webroot --webroot-path=/usr/share/nginx/html --email lucas.plath@gmail.com --agree-tos --no-eff-email --force-renewal -v -d www.react-panda.com -d react-panda.com
    # command: certonly --webroot --webroot-path=/usr/share/nginx/html --email lucas.plath@gmail.com --agree-tos --no-eff-email -v -n -d www.react-panda.com -d react-panda.com

volumes:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /root
      o: bind
  dhparam:
    driver: local
    driver_opts:
      type: none
      device: /root/dhparam/
      o: bind

networks:
  node-network:
    driver: bridge  